spring:
  datasource:
    url: jdbc:mysql://oai-mysql:3306/mytestdb?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

# knife4j-redis-lettuce配置
knife4j:
  redis:
    # 序列化方式
    jsonSerialType: Fastjson
    # redis ip
    host: 192.168.1.106
    password:
    # redis port
    port: 6379    
    # redis databases
    databases: [ 7 ]
    timeout: 60s
    lettuce:
      pool:
        max-active: 50
        max-wait: -1ms
        max-idle: 8
        min-idle: 0